"""Add processed_items

Revision ID: dc76a6668393
Revises: 
Create Date: 2026-03-16 11:15:59.080883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc76a6668393'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=512), nullable=False, comment='Original RSS item GUID or link'),
    sa.Column('author_source', sa.String(length=255), nullable=False, comment='RSS feed source name'),
    sa.Column('original_title', sa.Text(), nullable=False, comment='Raw news title'),
    sa.Column('translated_text', sa.Text(), nullable=False, comment='LLM-generated Russian summary'),
    sa.Column('image_url', sa.Text(), nullable=True, comment='URL of the attached media (if any)'),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True, comment='Message ID returned by Telegram after posting'),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_index('ix_processed_items_item_id', 'processed_items', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_processed_items_item_id', table_name='processed_items')
    op.drop_table('processed_items')
    # ### end Alembic commands ###
